name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify the desired Python version

      - name: Build and package using Docker
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false  # Set to true if you want to push the Docker image

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Executable
          path: ./dist/  # Adjust the path to the location of the generated .exe file
